version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - FIBER_ADDR=:3001

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app  # Монтируем код
      - /app/node_modules  # Исключаем node_modules
    command: npm run start  # Запускаем dev-сервер
networks:
  app-network:
    driver: bridge
