// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: crud_order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_name, customer_lastname, adress, event_date, total_price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateOrderParams struct {
	CustomerName     string           `json:"customer_name"`
	CustomerLastname string           `json:"customer_lastname"`
	Adress           string           `json:"adress"`
	EventDate        pgtype.Timestamp `json:"event_date"`
	TotalPrice       pgtype.Numeric   `json:"total_price"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerName,
		arg.CustomerLastname,
		arg.Adress,
		arg.EventDate,
		arg.TotalPrice,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

type CreateOrderItemsParams struct {
	OrderID  *int32         `json:"order_id"`
	DishID   *int32         `json:"dish_id"`
	Quantity int32          `json:"quantity"`
	Total    pgtype.Numeric `json:"total"`
}
