// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Dish struct {
	ID          int32   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ImageUrl    *string `json:"image_url"`
	Price       float64 `json:"price"`
}

type DishCategory struct {
	DishID     int32 `json:"dish_id"`
	CategoryID int32 `json:"category_id"`
}

type Order struct {
	ID               int32            `json:"id"`
	CustomerName     string           `json:"customer_name"`
	CustomerLastname string           `json:"customer_lastname"`
	Adress           string           `json:"adress"`
	EventDate        pgtype.Timestamp `json:"event_date"`
	Status           *string          `json:"status"`
	TotalPrice       pgtype.Numeric   `json:"total_price"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type OrderItem struct {
	ID       int32          `json:"id"`
	OrderID  *int32         `json:"order_id"`
	DishID   *int32         `json:"dish_id"`
	Quantity int32          `json:"quantity"`
	Total    pgtype.Numeric `json:"total"`
}

type Review struct {
	ID        int32            `json:"id"`
	OrderID   *int32           `json:"order_id"`
	Rating    int32            `json:"rating"`
	Comment   *string          `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
